services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "0.0.0.0:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: useradmin
      MONGO_INITDB_ROOT_PASSWORD: useradmin
      MONGO_INITDB_DATABASE: cpf-management
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
  backend-go:
    build: 
      context: . 
      dockerfile: Dockerfile 
    image: cpf-management/backend:1.0.0
    container_name: backend
    restart: on-failure
    ports:
      - "0.0.0.0:8889:8800"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: useradmin
      MONGO_PASS: useradmin
      PORT: 8800
    depends_on:
      - mongodb
    networks:
      - mongo-network
  
networks:
  mongo-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local