### Variables
@URL = http://localhost:8889
@APIURL = {{URL}}/api/v1/cliente

### ping da API
GET {{URL}}/ping

### ping da API
GET {{URL}}/status

### Get cliente por ID não encontrado
GET {{APIURL}}/a1b2c3d4-e5f6-1234-5678-90abcdef1234
Accept: application/json

### Get cliente por ID encontrado
GET {{APIURL}}/43310521-a934-11f0-ae2b-fabc94dc9b50
Accept: application/json

### Get todos os clientes
GET {{APIURL}}/
Accept: application/json

### Get todos os clientes com paginação
GET {{APIURL}}?page=1&limit=2
Accept: application/json

### Adicionar um cliente 1
POST {{APIURL}}/
Content-Type: application/json

{
    "nome": "cliente 1",
    "documento": "71248609973",
    "telefone": "48999448384",
    "bloqueado": false
}

### Adicionar um cliente 2
POST {{APIURL}}/
Content-Type: application/json

{
    "nome": "cliente 2",
    "documento": "71248609973",
    "telefone": "48999448384"
}

### Deleta um cliente
DELETE {{APIURL}}/a1b2c3d4-e5f6-1234-5678-90abcdef1234
Content-Type: application/json

### Alterar um cliente
PUT {{APIURL}}/43310521-a934-11f0-ae2b-fabc94dc9b50
Content-Type: application/json

{
    "nome": "cliente 333",
    "documento": "71248609972",
    "telefone": "48999448383",
    "bloqueado": false
}