// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/cliente/usecases/getall/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/cliente/usecases/getall/interfaces.go -destination=internal/modules/cliente/usecases/getall/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/valdinei-santos/cpf-backend/internal/modules/cliente/infra/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIUsecase is a mock of IUsecase interface.
type MockIUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIUsecaseMockRecorder
	isgomock struct{}
}

// MockIUsecaseMockRecorder is the mock recorder for MockIUsecase.
type MockIUsecaseMockRecorder struct {
	mock *MockIUsecase
}

// NewMockIUsecase creates a new mock instance.
func NewMockIUsecase(ctrl *gomock.Controller) *MockIUsecase {
	mock := &MockIUsecase{ctrl: ctrl}
	mock.recorder = &MockIUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsecase) EXPECT() *MockIUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIUsecase) Execute(page, size int64) (*dto.ResponseManyPaginated, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", page, size)
	ret0, _ := ret[0].(*dto.ResponseManyPaginated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIUsecaseMockRecorder) Execute(page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIUsecase)(nil).Execute), page, size)
}
